Introduce StrEnum and IntEnum classes to resolve unit test failures with Python 3.11+ (#5397)
# Description

Fix the following unit test failure when running with Python 3.11+. More
background information about this issue is discussed in
https://github.com/mobilityhouse/ocpp/issues/447.

```
FAIL: test_create_endpoint_dbt_yaml_with_parent_pipelines (tests.api.endpoints.test_blocks.DBTBlockAPIEndpointTest.test_create_endpoint_dbt_yaml_with_parent_pipelines)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/async_case.py", line 90, in _callTestMethod
    if self._callMaybeAsync(method) is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/async_case.py", line 112, in _callMaybeAsync
    return self._asyncioRunner.run(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/hw/workspace/dev/mage-ai/mage_ai/tests/api/endpoints/mixins.py", line 247, in _test_create_endpoint
    await self.build_test_create_endpoint(
  File "/Users/hw/workspace/dev/mage-ai/mage_ai/tests/api/endpoints/mixins.py", line 813, in build_test_create_endpoint
    validation = assert_after_create_count(self)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hw/workspace/dev/mage-ai/mage_ai/tests/api/endpoints/test_blocks.py", line 154, in __assert_after_create_yaml
    self.assertEqual({
AssertionError: {'dbt[56 chars]h': 'dbts/dbt_yaml.yaml', 'project_path': 'dbt/test_project'}} != {'dbt[56 chars]h': 'BlockType.DBTs/dbt_yaml.yaml', 'project_p[21 chars]ct'}}
  {'dbt_project_name': 'dbt/test_project',
-  'file_source': {'path': 'dbts/dbt_yaml.yaml',
?                           ^^^

+  'file_source': {'path': 'BlockType.DBTs/dbt_yaml.yaml',
?                           ^^^^^^^^^^^^^

                   'project_path': 'dbt/test_project'}}

----------------------------------------------------------------------
Ran 27 tests in 2.061s

FAILED (failures=1)
```

# How Has This Been Tested?
<!-- Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
-->

- [X] Tested with a local development environment.

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature,
documentation)
- [X] I have performed a self-review of my own code
- [ ] I have added unit tests that prove my fix is effective or that my
feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

cc:
<!-- Optionally mention someone to let them know about this pull request
-->
@wangxiaoyou1993